### ISSUE TITLE
out of memory with 'netlifyctl deploy'

### ISSUE THREAD

**Issue by rockonedege** [netlify/netlifyctl#106]
I just downloaded the pre-built Linux version and experimented with my site, It failed with the following log.
environment: Linux version 4.13.0-39-generic (buildd@lgw01-amd64-038) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3.2)) #44-Ubuntu SMP Thu Apr 5 14:25:01 UTC 2018

it looks like some memory leak as my laptop has 8GB memory with nothing else but Firefox on while running the command.

> CCCCCCCCCCounting objects: 494 total objects  ✔
RRRRResolving deltas: 3 objects to upload  ✔
UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUploading objects: 0/3 🌎UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUploading objects: 0/3 🌍UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUploading objects: 0/3 🌏UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUploading objects: 0/3 🌎UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUploading objects: 0/3 🌍UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUploading objects: 0/3 🌎UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUploading objects: 0/3 🌏UUUUUUUUUUUUUUUUUUUUploading objects  ✘     
fatal error: runtime: out of memory

> runtime stack:
runtime.throw(0xcb150b, 0x16)
	/usr/local/go/src/runtime/panic.go:619 +0x81
runtime.sysMap(0xc6d9b10000, 0xbc860000, 0x0, 0x11bfcf8)
	/usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x11a6880, 0xbc860000, 0x1)
	/usr/local/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x11a6880, 0x5e42d, 0x0)
	/usr/local/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0x11a6880, 0x5e42d, 0x11bfd08, 0x2cd16)
	/usr/local/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0x11a6880, 0x5e42d, 0x101, 0xc4205d9f10)
	/usr/local/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0x11a6880, 0x5e42d, 0xc420010101, 0xc42047bc80)
	/usr/local/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0xbc858f0f, 0x11a0101, 0xc42047bc01)
	/usr/local/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x11a4e74100000000)
	/usr/local/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1170

> goroutine 31 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:363 fp=0xc4205d7658 sp=0xc4205d7650 pc=0x454000
runtime.mallocgc(0xbc858f0f, 0xb29d40, 0x45f701, 0xc4205d7730)
	/usr/local/go/src/runtime/malloc.go:720 +0x8a2 fp=0xc4205d76f8 sp=0xc4205d7658 pc=0x4109c2
runtime.makeslice(0xb29d40, 0xbc858f0f, 0xbc858f0f, 0xc420146070, 0x410c68, 0x11be250)
	/usr/local/go/src/runtime/slice.go:61 +0x77 fp=0xc4205d7728 sp=0xc4205d76f8 pc=0x43ff07
bytes.makeSlice(0xbc858f0f, 0x0, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:230 +0x6d fp=0xc4205d7768 sp=0xc4205d7728 pc=0x4d18dd
bytes.(*Buffer).grow(0xc4201476c0, 0x2cd15425, 0x506d3d)
	/usr/local/go/src/bytes/buffer.go:144 +0x151 fp=0xc4205d77b8 sp=0xc4205d7768 pc=0x4d1291
bytes.(*Buffer).Write(0xc4201476c0, 0xc5f6424000, 0x2cd15425, 0x59a2a849, 0x59a2a849, 0x0, 0x0)
	/usr/local/go/src/bytes/buffer.go:174 +0xd9 fp=0xc4205d77e8 sp=0xc4205d77b8 pc=0x4d1569
github.com/netlify/netlifyctl/vendor/github.com/sirupsen/logrus.Entry.log(0xc4200ae140, 0xc4203a2060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb29a05, ...)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/sirupsen/logrus/entry.go:113 +0x357 fp=0xc4205d78c8 sp=0xc4205d77e8 pc=0x504fe7
github.com/netlify/netlifyctl/vendor/github.com/sirupsen/logrus.(*Entry).Debug(0xc4203a40f0, 0xc4205d7980, 0x1, 0x1)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/sirupsen/logrus/entry.go:130 +0xaa fp=0xc4205d7938 sp=0xc4205d78c8 pc=0x5052da
github.com/netlify/netlifyctl/vendor/github.com/sirupsen/logrus.(*Entry).Debugf(0xc4203a40f0, 0xc5c9712000, 0x2cd10b19, 0x0, 0x0, 0x0)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/sirupsen/logrus/entry.go:178 +0xef fp=0xc4205d79a0 sp=0xc4205d7938 pc=0x5058df
github.com/netlify/netlifyctl/vendor/github.com/go-openapi/runtime/client.(*Runtime).Submit(0xc420326000, 0xc42041c3c0, 0x0, 0x0, 0x0, 0x0)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/go-openapi/runtime/client/runtime.go:277 +0xbec fp=0xc4205d7b28 sp=0xc4205d79a0 pc=0x795b8c
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/plumbing/operations.(*Client).UploadDeployFile(0xc4203be100, 0xc420519860, 0xd2b0a0, 0xcd49d0, 0x0, 0x1, 0x2)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/plumbing/operations/operations_client.go:2066 +0x30f fp=0xc4205d7b78 sp=0xc4205d7b28 pc=0x806bdf
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.(*Netlify).uploadFile.func2(0x0, 0x0)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:409 +0x5fa fp=0xc4205d7c68 sp=0xc4205d7b78 pc=0x85edda
github.com/netlify/netlifyctl/vendor/github.com/cenkalti/backoff.RetryNotify(0xc4207041e0, 0xd2c680, 0xc420704180, 0x0, 0xcfe3b001, 0xc4207041e0)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/cenkalti/backoff/retry.go:37 +0x88 fp=0xc4205d7d58 sp=0xc4205d7c68 pc=0x844d68
github.com/netlify/netlifyctl/vendor/github.com/cenkalti/backoff.Retry(0xc4207041e0, 0xd2c680, 0xc420704180, 0x0, 0xc420482f08)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/cenkalti/backoff/retry.go:25 +0x48 fp=0xc4205d7d98 sp=0xc4205d7d58 pc=0x844cb8
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.(*Netlify).uploadFile(0xc4203be120, 0x7ff0ac42e9a8, 0xc4203a2630, 0xc4203521c0, 0xc42051df40, 0xd35500, 0xc420078140, 0x0, 0x0, 0xc4203f48c0, ...)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:386 +0x4b7 fp=0xc4205d7f80 sp=0xc4205d7d98 pc=0x85bf37
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4205d7f88 sp=0xc4205d7f80 pc=0x456b21
created by github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.(*Netlify).uploadFiles
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:343 +0x3a1

> goroutine 1 [semacquire, 7 minutes]:
sync.runtime_Semacquire(0xc4203f48cc)
	/usr/local/go/src/runtime/sema.go:56 +0x39
sync.(*WaitGroup).Wait(0xc4203f48c0)
	/usr/local/go/src/sync/waitgroup.go:129 +0x72
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.(*Netlify).uploadFiles(0xc4203be120, 0x7ff0ac42e9a8, 0xc4203a2630, 0xc4203521c0, 0xc4203be860, 0xd35500, 0xc420078140, 0x0, 0x0, 0x4ded5d, ...)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:348 +0x461
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.(*Netlify).DoDeploy(0xc4203be120, 0x7ff0ac42e9a8, 0xc4203a2630, 0xc4203880a0, 0xc4203521c0, 0xbc3500, 0xbe7440, 0xc420440400)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:262 +0x96e
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.(*Netlify).DeploySite(0xc4203be120, 0x7ff0ac42e9a8, 0xc4203a2630, 0xc4200a41e0, 0x24, 0xc4200a4210, 0x24, 0x0, 0x0, 0x0, ...)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:144 +0x98
github.com/netlify/netlifyctl/commands/deploy.(*deployCmd).deploySite(0xc42013aea0, 0x7ff0ac42e9e0, 0xc4203a2630, 0xc4202bf200, 0x11be250, 0x0, 0x0, 0xd31200, 0x7ff0ac42e9e0)
	/home/david/src/github.com/netlify/netlifyctl/commands/deploy/deploy.go:89 +0x62f
github.com/netlify/netlifyctl/commands/deploy.(*deployCmd).(github.com/netlify/netlifyctl/commands/deploy.deploySite)-fm(0x7ff0ac42e9e0, 0xc4203a2630, 0xc4202bf200, 0x11be250, 0x0, 0x0, 0xc282a0, 0xc4203a2270)
	/home/david/src/github.com/netlify/netlifyctl/commands/deploy/deploy.go:45 +0x69
github.com/netlify/netlifyctl/commands/middleware.SiteConfigMiddleware.func1(0x7ff0ac42e9e0, 0xc4203a2270, 0xc4202bf200, 0x11be250, 0x0, 0x0, 0x1, 0xc4203a21b0)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:222 +0x252
github.com/netlify/netlifyctl/commands/middleware.ClientMiddleware.func1(0x7ff0ac42e9e0, 0xc4203a20f0, 0xc4202bf200, 0x11be250, 0x0, 0x0, 0x81b82f, 0xbc3500)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:183 +0x339
github.com/netlify/netlifyctl/commands/middleware.AuthMiddleware.func1(0x7ff0ac42e9e0, 0xc4203a2090, 0xc4202bf200, 0x11be250, 0x0, 0x0, 0x11a10a0, 0xd23250)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:128 +0x1ca
github.com/netlify/netlifyctl/commands/middleware.LoggingMiddleware.func1(0x7ff0ac3db1a8, 0xc4200a8030, 0xc4202bf200, 0x11be250, 0x0, 0x0, 0xc4203e2570, 0xc4202b9b80)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:116 +0x1f1
github.com/netlify/netlifyctl/commands/middleware.DebugMiddleware.func1(0x7ff0ac3db1a8, 0xc4200a8030, 0xc4202bf200, 0x11be250, 0x0, 0x0, 0x0, 0x0)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:89 +0x4bb
github.com/netlify/netlifyctl/commands/middleware.NewRunFunc.func1(0xc4202bf200, 0x11be250, 0x0, 0x0, 0x0, 0x0)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:52 +0xf2
github.com/netlify/netlifyctl/vendor/github.com/spf13/cobra.(*Command).execute(0xc4202bf200, 0x11be250, 0x0, 0x0, 0xc4202bf200, 0x11be250)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/spf13/cobra/command.go:644 +0x3db
github.com/netlify/netlifyctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x118f980, 0x11bdebc, 0xca05bc, 0x3)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/spf13/cobra/command.go:734 +0x2d4
github.com/netlify/netlifyctl/commands.Execute()
	/home/david/src/github.com/netlify/netlifyctl/commands/netlify.go:41 +0x29b
main.main()
	/home/david/src/github.com/netlify/netlifyctl/main.go:16 +0x79

> goroutine 18 [syscall, 7 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

> goroutine 5 [select, 7 minutes, locked to thread]:
runtime.gopark(0xcd5f30, 0x0, 0xca307f, 0x6, 0x18, 0x1)
	/usr/local/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc420052750, 0xc42009a780)
	/usr/local/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2361 +0x1

> goroutine 49 [chan receive, 7 minutes]:
github.com/netlify/netlifyctl/commands/middleware.DebugMiddleware.func1.1(0xc42013b3e0, 0x0, 0xc4201476c0)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:79 +0x38
created by github.com/netlify/netlifyctl/commands/middleware.DebugMiddleware.func1
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:78 +0x464

> goroutine 30 [chan send, 5 minutes]:
github.com/netlify/netlifyctl/operations.(*DeployObserver).OnFailedUpload(0xc420078140, 0xc42051dcc0)
	/home/david/src/github.com/netlify/netlifyctl/operations/deploy.go:87 +0x3b
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.(*Netlify).uploadFile(0xc4203be120, 0x7ff0ac42e9a8, 0xc4203a2630, 0xc4203521c0, 0xc42051dcc0, 0xd35500, 0xc420078140, 0x0, 0x0, 0xc4203f48c0, ...)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:437 +0x56b
created by github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.(*Netlify).uploadFiles
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:343 +0x3a1

**Comment by cipriancraciun** [comment]
I have encountered a similar issue, and I think I've linked it to large files (around 100 MiB) in size.

Although I haven't sought the problem in the code, I've applied the following workarounds (by writing a wrapper `bash` script, which works only on Linux):
* use `ulimit -m 4194304 -d 4194304` to make sure that it will never eat more than 4 GiB of RAM;
* use `printf -- 1000 >| "/proc/${$}/oom_score_adj"` to make sure that when the out-of-memory-killer runs it will hit `netlifyctl` and not other processes (most often a browser);
* `export -- GOMAXPROCS=1` -- I doubt it actually helps, but at least I hope to reduce the stress on the system under memory pressure;
* `export -- GOGC=5` -- make the Go's garbage collector more aggressive (it helps somewhat);
* `export -- GODEBUG=gcstoptheworld=1,madvdontneed=1` -- it makes Go pause when garbage collecting (which again helps with the OOM killer), and hopefully unused memory is marked as unused so the OS can skip swapping;

However, none of these measures actually solve the problem, they just delay the crash sometimes.

Luckily if you run the `netlifyctl deploy` command in a loop, it will eventually push everything.

**Comment by cipriancraciun** [comment]
I found the issue, namely the memory leak is due to the logging done in the `DebugMiddleware` function.  What happens:
* in order to output the `netlifyctl-debug.log` file (which is enabled by the `--debug` flag, but also written in case of failure),
* the logger is instructed to write the log to a buffer (see https://github.com/netlify/netlifyctl/blob/master/commands/middleware/middleware.go#L57-L66);
* unfortunately one of the dependencies (I think `github.com/netlify/open-api`) also uses the logger to trace all HTTP calls, which unfortunately includes in the request body the original file;
* thus when large uploads are involved, all the files are stored in the logging buffer;

I've made the following patch, which unless it receives the `--debug` flag it won't save that file, and it increases the log level to warnings:
https://github.com/cipriancraciun/netlifyctl/commit/0167fe06b5179d542060f163694f7b3f23169e0e

(I could have completely removed that buffer, but I don't want to touch the code too much...)
