### ISSUE TITLE
Failed to publish site using v0.2.0 binaries

### ISSUE THREAD

**Issue by rozhok** [netlify/netlifyctl#63]
```
netlifyctl deploy -A 9e06ca34686***0b3c69e0e
Counting objects .... 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x84ca01]

goroutine 1 [running]:
github.com/netlify/netlifyctl/operations.(*DeployObserver).OnSuccessfulStep(0xc4200103c0, 0xc4202a05a0, 0xa, 0xc4202a05a0)
	/home/david/src/github.com/netlify/netlifyctl/operations/deploy.go:43 +0xc1
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.walk.func1(0xc4200a0240, 0x89, 0x10559e0, 0xc42051e4e0, 0x0, 0x0, 0x0, 0x0)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:480 +0x343
path/filepath.walk(0xc4200a0240, 0x89, 0x10559e0, 0xc42051e4e0, 0xc4202a0540, 0x0, 0x0)
	/usr/local/go/src/path/filepath/path.go:351 +0x81
path/filepath.walk(0xc420520380, 0x7e, 0x10559e0, 0xc42051e410, 0xc4202a0540, 0x0, 0x30)
	/usr/local/go/src/path/filepath/path.go:376 +0x414
path/filepath.Walk(0xc420520380, 0x7e, 0xc4202a0540, 0x0, 0xc4202a0510)
	/usr/local/go/src/path/filepath/path.go:398 +0x14c
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.walk(0xc420520380, 0x7e, 0x1056920, 0xc4200103c0, 0x0, 0x0, 0xc4200a5680)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:487 +0x1be
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.(*Netlify).DoDeploy(0xc42051c420, 0x7fec00ee8f98, 0xc42020cb10, 0xc4200a01b0, 0x0, 0xba29a0, 0xbc3d00, 0xc42051a400)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:173 +0xc5
github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain.(*Netlify).DeploySite(0xc42051c420, 0x7fec00ee8f98, 0xc42020cb10, 0xc4202a00f0, 0x24, 0xc420520380, 0x7e, 0x0, 0x0, 0x0, ...)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/netlify/open-api/go/porcelain/deploy.go:153 +0x9d
github.com/netlify/netlifyctl/commands/deploy.(*deployCmd).deploySite(0xc420324ba0, 0x7fec00ee8f58, 0xc42020cb10, 0xc42052cb40, 0xc42051c3c0, 0x0, 0x2, 0xc4201918b0, 0x84f912)
	/home/david/src/github.com/netlify/netlifyctl/commands/deploy/deploy.go:85 +0x61b
github.com/netlify/netlifyctl/commands/deploy.(*deployCmd).(github.com/netlify/netlifyctl/commands/deploy.deploySite)-fm(0x7fec00ee8f58, 0xc42020cb10, 0xc42052cb40, 0xc42051c3c0, 0x0, 0x2, 0x0, 0x10a3da0)
	/home/david/src/github.com/netlify/netlifyctl/commands/deploy/deploy.go:44 +0x69
github.com/netlify/netlifyctl/commands/middleware.DebugMiddleware.func1(0x7fec00ee8f58, 0xc42020cb10, 0xc42052cb40, 0xc42051c3c0, 0x0, 0x2, 0x0, 0x0)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:87 +0x509
github.com/netlify/netlifyctl/commands/middleware.LoggingMiddleware.func1(0x7fec00ee8f58, 0xc42020cab0, 0xc42052cb40, 0xc42051c3c0, 0x0, 0x2, 0x10534a0, 0xc42007e158)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:113 +0x1f7
github.com/netlify/netlifyctl/commands/middleware.AuthMiddleware.func1(0x7fec00ee8f58, 0xc42020ca20, 0xc42052cb40, 0xc42051c3c0, 0x0, 0x2, 0x1, 0xc42020c960)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:124 +0x1d4
github.com/netlify/netlifyctl/commands/middleware.ClientMiddleware.func1(0x7fec00ee8ed8, 0xc42007e158, 0xc42052cb40, 0xc42051c3c0, 0x0, 0x2, 0xc687bd, 0x4)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:177 +0x316
github.com/netlify/netlifyctl/commands/middleware.NewRunFunc.func1(0xc42052cb40, 0xc42051c3c0, 0x0, 0x2, 0x0, 0x0)
	/home/david/src/github.com/netlify/netlifyctl/commands/middleware/middleware.go:52 +0xf5
github.com/netlify/netlifyctl/vendor/github.com/spf13/cobra.(*Command).execute(0xc42052cb40, 0xc42051c220, 0x2, 0x2, 0xc42052cb40, 0xc42051c220)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/spf13/cobra/command.go:644 +0x3ef
github.com/netlify/netlifyctl/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1095c60, 0x10bf6b7, 0xc67fba, 0x3)
	/home/david/src/github.com/netlify/netlifyctl/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/netlify/netlifyctl/commands.Execute()
	/home/david/src/github.com/netlify/netlifyctl/commands/netlify.go:41 +0x2a5
main.main()
	/home/david/src/github.com/netlify/netlifyctl/main.go:16 +0x7e
```

After downgrading to v0.1.5 everything went well.

**Comment by calavera** [comment]
Sorry for the trouble. I just published the version v0.2.1 that fixes this problem. Thanks a lot for reporting it 🙌
